(defglobal
    ?*POINTS-EPISODE-END-FAILURE* = -1
    ?*POINTS-EPISODE-END-SUCCESS* = 1
    ?*POINTS-ACTION-SPAWN-AND-TRANSPORT* = 0
    ?*POINTS-ACTION-TRANSPORT* = 0
    ?*POINTS-ACTION-PAY-WITH-CARRIER* = 0
    ?*POINTS-ACTION-CARRIER-TO-INPUT* = 0
    ?*POINTS-ACTION-PAY-FROM-BS* = 0
    ?*POINTS-ACTION-TRANSPORT-TO-SLIDE* = 0
    ?*POINTS-ACTION-BASE-TRANSPORT* = 0
)