(defglobal
    ?*CX-RL-REWARD-EPISODE-FAILURE* = -50
    ?*CX-RL-REWARD-EPISODE-SUCCESS* = 50
    ?*POINTS-ACTION-TRANSPORT* = 0
    ?*POINTS-ACTION-PAY-WITH-CARRIER* = 0
    ?*POINTS-ACTION-CARRIER-TO-INPUT* = 0
    ?*POINTS-ACTION-PAY-WITH-BASE* = 0
    ?*POINTS-ACTION-TRANSPORT-TO-CS* = 0
    ?*POINTS-ACTION-BS-DISPENSE* = 0
    ?*POINTS-ACTION-BS-DISPENSE-PAY* = -1
)