(defglobal
    ?*POINTS-EPISODE-END-FAILURE* = 0
    ?*POINTS-EPISODE-END-SUCCESS* = 0
    ?*POINTS-ACTION-TRANSPORT* = 0
    ?*POINTS-ACTION-PAY-WITH-CARRIER* = 0
    ?*POINTS-ACTION-CARRIER-TO-INPUT* = 0
    ?*POINTS-ACTION-PAY-WITH-BASE* = 0
    ?*POINTS-ACTION-TRANSPORT-TO-CS* = 0
    ?*POINTS-ACTION-BS-DISPENSE* = 0
    ?*POINTS-ACTION-BS-DISPENSE-PAY* = -1
)