clips_manager:
  ros__parameters:
    environments: ["main"]
    main:
        plugins: ["executive",
                  "ament_index",
                  "config",
                  "ros_msgs",
                  "create_rl_env_state",
                  "exec_action_selection",
                  "get_observable_objects",
                  "get_observable_predicates",
                  "get_predefined_observables",
                  "get_action_list",
                  "get_action_list_robot",
                  "set_rl_mode",
                  "get_free_robot",
                  "action_selection",
                  "reset_cx",
                  "plan_temporal_action",
                  "pddl_files",
                  "files"]
        log_clips_to_file: true
        watch: ["facts", "rules"]
        redirect_stdout_to_debug: true

    ament_index:
      plugin: "cx::AmentIndexPlugin"
    
    config:
      plugin: "cx::ConfigPlugin"

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    
    create_rl_env_state:
      plugin: "cx::CXCxRlInterfacesCreateRLEnvStatePlugin"

    exec_action_selection:
      plugin: "cx::CXCxRlInterfacesExecActionSelectionPlugin"

    get_observable_objects:
      plugin: "cx::CXCxRlInterfacesGetObservableObjectsPlugin"
    
    get_observable_predicates:
      plugin: "cx::CXCxRlInterfacesGetObservablePredicatesPlugin"

    get_predefined_observables:
      plugin: "cx::CXCxRlInterfacesGetPredefinedObservablesPlugin"

    get_action_list:
      plugin: "cx::CXCxRlInterfacesGetActionListPlugin"

    get_action_list_robot:
      plugin: "cx::CXCxRlInterfacesGetActionListRobotPlugin"

    set_rl_mode:
      plugin: "cx::CXCxRlInterfacesSetRLModePlugin"

    get_free_robot:
      plugin: "cx::CXCxRlInterfacesGetFreeRobotPlugin"

    action_selection:
      plugin: "cx::CXCxRlInterfacesActionSelectionPlugin"

    reset_cx:
      plugin: "cx::CXCxRlInterfacesResetCXPlugin"

    plan_temporal_action:
      plugin: "cx::CXCxPddlMsgsPlanTemporalPlugin"
    
    pddl_files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_pddl_clips", "expertino"]
      batch: [
        "clips/deftemplates.clp",
        "clips/expertino/pddl/deftemplates-overrides.clp",
        "clips/pddl-no-deftemplates.clp"
        ]

    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["expertino", "cx_rl_clips", "expertino_blocksworld"]
      load: [
        # Specific isolated concepts
        "clips/expertino/start-tasks/start-tasks.clp",
        # General utility stuff
        "clips/expertino/defglobals.clp",
        "clips/expertino/deftemplates.clp",
        # Startup
        "clips/expertino_blocksworld/init-pddl.clp",
        # PDDL
        "clips/expertino_blocksworld/pddl/instances.clp",
        "clips/expertino_blocksworld/point-mapping.clp",
        "clips/cx_rl_clips/reinforcementlearning.clp",
        "clips/cx_rl_clips/reset-game.clp",
        "clips/cx_rl_clips/rl-utils.clp",
        "clips/cx_rl_clips/create-rl-env-state-srv.clp",
        "clips/cx_rl_clips/exec-action-selection-client.clp",
        "clips/cx_rl_clips/get-observable-objects-srv.clp",
        "clips/cx_rl_clips/get-observable-predicates-srv.clp",
        "clips/cx_rl_clips/get-predefined-observables-srv.clp",
        "clips/cx_rl_clips/get-action-list-srv.clp",
        "clips/cx_rl_clips/get-action-list-robot-srv.clp",
        "clips/cx_rl_clips/set-rl-mode-srv.clp",
        "clips/cx_rl_clips/get-free-robot-action.clp",
        "clips/cx_rl_clips/action-selection-action.clp",
        "clips/cx_rl_clips/reset-cx-action.clp",
        "clips/expertino_blocksworld/init.clp",
        "clips/expertino_blocksworld/reset.clp",
        "clips/expertino_blocksworld/action-executability.clp",
        "clips/expertino_blocksworld/action-execution.clp"
        ]
    ros_msgs:
      plugin: "cx::RosMsgsPlugin"


        
