planner_server:
  ros__parameters:
    # Configuration for NavfnPlanner plugin
    NavfnPlanner:
      # Use the NavfnPlanner as the global planner
      planner_plugin: "nav2_navfn_planner/NavfnPlanner"

      # Parameters specific to the NavfnPlanner
      nav2_navfn_planner:
        # Set the tolerance for planner goal reaching
        tolerance: 0.1
        # Set the maximum number of iterations for the planner
        max_iterations: 10000
        # Set the distance the robot can oscillate before planning is considered failed
        oscillation_timeout: 0.0
        # Set the distance the robot can move without causing oscillation
        oscillation_distance: 0.5

