clips_executive:
  ros__parameters:
    # If CLIPS debugging is enabled, certain rules and facts can be excluded
    # from watching, e.g. if they are showing up at too high frequencies or
    # are not of interest.
    unwatch_facts: ["time"]
    unwatch_rules: ["time-retract"]

    # If set to true, will trigger the assertion of a (time (now)) fact in
    # each loop. This can be used to trigger loop events in CLIPS.
    assert_time_each_loop: true

    # Sets the frequency, in which the clips agenda is being refresh
    # inside the CX (in HZ)
    refresh_rate: 1

    # If set to true, goals will be cleaned automatically when they
    # reach the RETRACTED state. Disabling be useful for debugging.
    # You need to manually cleanup goals (and associated data such as
    # plans) to keep things tidy.
    automatic-goal-retraction: true

    init:
      # Files are relative pathes to the share directory of the cx_clips_executive
      # and the path specified through agent_dir
      # These files are loaded from the cx_clips_executive package
      - name: utils
        files:
          - defglobals.clp
          - deftemplates.clp
      - name: clips-executive
        files:
          - core/plan.clp
          - core/domain.clp
          - core/skills.clp
          - core/pddl.clp
          - core/skills-actions.clp
      - name: init
        files:
         - deffunctions.clp
         - init.clp
      - name: goal-reasoner
        files:
          - goal-formulation.clp
          - goal-selection.clp
          - goal-expansion.clp
          - goal-commitment.clp
          - goal-dispatch.clp
          - goal-evaluation.clp
      - name: action-selection
        file: action-selection.clp
      - name: refbox-comm
        files:
          - refbox-comm-init.clp
          - refbox-recv.clp
       # Map plan actions to skill strings.
    action_mapping:
      move:
        mapped_to: say{text="hello world"}
        executor: dummy_skiller

    parameters:
      simtest:
        enabled: false
        testbed: FULL  # defined in simtest.clp
      rcll:
        peer_address: 127.0.0.1
        peer_recv_port: 4444
        peer_send_port: 4445
        cyan_recv_port: 4441
        magenta_recv_port: 4442
        cyan_send_port: 4446
        magenta_send_port: 4447

        team_name: Carologistics
        crypto_key: randomkey
        cipher: "aes-128-cbc"
