clips_features_manager:
  ros__parameters:
    clips_features_list: ["pddl_parser", "skill_execution", "protobuf", "plansys2"]
    clips_features:
      mock_feature:
        plugin: "cx::MockFeature"
      plansys2:
        plugin: "cx::Plansys2Feature"
      pddl_parser:
        plugin: "cx::PddlParserFeature"
      skill_execution:
        plugin: "cx::SkillExecutionFeature"
      protobuf:
        plugin: "cx::ProtobufFeature"
        feature_parameters: ["protobuf_path"]
        protobuf_path:
          # This path assumes relativeness to agent_dir
          value: "rcll-protobuf-msgs"
          type: "string"
      # navgraph_compute:
      #   plugin: "cx::NavGraphCompute"
      # navgraph_set_bounding_box:
      #   plugin: "cx::NavGraphSetBoundingBox"
      # navgraph_generate_waitzones:
      #   plugin: "cx::NavGraphGenerateWaitzones"
      # navgraph_update_station_by_tag:
      #   plugin: "cx::NavGraphUpdateStationByTag"

