/**:
  ros__parameters:

    model_name: "ExpertinoAgent"

    training:
      retraining: false
      max_episodes: 500
      timesteps: 100000000

    env:
      entrypoint: "expertino_rl.expertino_env:ExpertinoEnv"

    model:
      learning_rate: 0.0003
      gamma: 0.99
      gae_lambda: 0.95
      ent_coef: 0.0
      vf_coef: 0.5
      max_grad_norm: 0.5
      batch_size: 64
      n_steps: 10
      seed: 42
      verbose: 1
      wait_for_all_robots: false

    
    